api:
  - https://vitalsource.atlassian.net/wiki/spaces/ZAI/pages/4591419583/Manage-related+APIs+Internal+Documentation
  - https://vitalsource.atlassian.net/wiki/spaces/ZAI/pages/4591420478/API+Documentation+Template
  - https://vitalsource.atlassian.net/wiki/spaces/ZAI/pages/4591419719/V4+Products
  - https://vitalsource.atlassian.net/wiki/spaces/ZAI/pages/4591419761/V3+Refunds+API

flows:
  - https://vitalsource.atlassian.net/wiki/spaces/CON/pages/3518955521/Manage+Development+Process
  - https://vitalsource.atlassian.net/wiki/spaces/ENG/pages/2077753873/Deploying+your+application

features:
  - https://vitalsource.atlassian.net/wiki/spaces/CON/pages/20216247/Understanding+distribution+sets+and+catalogs
  - https://vitalsource.atlassian.net/wiki/spaces/CON/pages/20217584/Building+catalogs
  - https://vitalsource.atlassian.net/wiki/spaces/CON/pages/20217579/Distribution+sets
  - https://vitalsource.atlassian.net/wiki/spaces/CON/pages/20217696/Store+content
  - https://vitalsource.atlassian.net/wiki/spaces/CON/pages/139493420/Distribution+Channels

misc:
  - https://vitalsource.atlassian.net/wiki/spaces/BOOKSHELF/pages/681017345/Engineering+Cheat+Sheet
  - https://vitalsource.atlassian.net/wiki/spaces/ENG/pages/2626257083/Engineering+Team+Names
  - https://vitalsource.atlassian.net/wiki/spaces/ENG/pages/2445377604/Engineering+All-Hand+Meetings
  -https://vitalsource.atlassian.net/wiki/spaces/~552874847/pages/2836267560/Specifications+Acceptance+Criteria+Refinement